apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: avernusx/otus-backend:0.1
        name: backend
        ports:
        - containerPort: 5000
        env:
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: DB_USER
          - name: DB_PASS
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: DB_PASS
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: DB_NAME
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: DB_HOST
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: DB_PORT
        livenessProbe:
          httpGet:
            port: 5000
            path: /liveness-probe
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            port: 5000
            path: /health
          initialDelaySeconds: 10
          periodSeconds: 5
