---
apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: database
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
    app: database

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database-statefulset
spec:
  serviceName: "database"
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: postgres:12.2
        ports:
        - containerPort: 5432
          name: postgredb
        env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: DB_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: DB_PASS
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: DB_NAME
        volumeMounts:
        - name: postgredb
          mountPath: /var/lib/databaseql/data
          subPath: database
  volumeClaimTemplates:
  - metadata:
      name: postgredb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi