image:
  repository: avernusx/otus-backend
  tag: "0.3.1"

replicaCount: 2

deployment:
  port: 5000

service:
  port: 5000
  
postgresql:
  enabled: true
  postgresqlUsername: dev
  postgresqlPassword: dev
  postgresqlDatabase: dev
  service:
    port: 5432
  initdbUser: "postgres"
  initdbScripts:
    db-init.sql: |
      CREATE EXTENSION if not exists pgcrypto;
  metrics:
    enabled: true
    service:
      type: NodePort
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9187"
      loadBalancerIP:
    serviceMonitor:
      enabled: true
      additionalLabels: {}
      namespace: default
      interval: 15s
      scrapeTimeout: 10s
      
metrics:
  serviceMonitor:
    enabled: true     

ingress:
  enabled: true
  hosts:
    - host: arch.homework
      paths: ["/otusapp"] 

ingressName: nginx-nginx-ingress-controller      