apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: entrypoint
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
        - path: /otusapp($|/)(.*)
          backend:
            serviceName: {{ include "app.fullname" . }}
            servicePort: {{ .Values.service.port }}