apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "app.labels" . | nindent 4 }}
  name: {{ include "app.fullname" . }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      name: web
      protocol: TCP
      targetPort: {{ .Values.deployment.port }}
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
  type: NodePort